name: stitch_utils
version: 0.3.1
config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_modules"]
macro-paths: ["macros"]
log-path: "logs"

require-dbt-version: [">=0.17.0", "<1.1.0"]
